### PR TITLE
Rough draft of blog post for Drone with Elixir demo.

### PR DESCRIPTION
**Pull request by aweiker**
Don't merge this in yet as I still need to go through the editing process. Just getting this PR started for comments and awareness.

### CODE REVIEW

**Comment by gtaylor** [comment]
@bradrydzewski As @aweiker mentioned, this isn't ready yet. But can we get this merged on _Tuesday_ night? #10 would ideally be on Monday night.

**Comment by aweiker** [comment]
I went through and made some edits. I think this should be ready now. Please do read and let me know how it goes.

**Comment by gtaylor** [comment]
@aweiker Could I pester you to update the date on the post to be Feb 10 tonight? I wanted to make sure this ends up as the latest post so you don't get stuffed behind my ECS post.

Reminding @bradrydzewski that this should be merged later tonight so that I can get the Tweet scheduled for tomorrow morning.

**Comment by aweiker** [comment]
It's ready. 

-Aaron

**Comment by gtaylor** [comment]
Thanks @aweiker and Brad! This is live on the blog now, with a Tweet scheduled for 7am PST tomorrow.

**Pull request merged**
